# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
- develop


pool:
  vmImage: ubuntu-latest


steps:
#- task: SonarQubePrepare@5
#  inputs:
#    SonarQube: 'SonarQube_AzureDevops'
#    scannerMode: 'Other'
    


- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'


- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube_AzureDevops'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Order_Management_Order_Management'
    cliSources: 'coit-frontend'

- script: |
    echo  '$(System.DefaultWorkingDirectory)'
    cd coit-frontend
    pwd
    npm install
    npm run build
  displayName: 'npm install and build'


- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '100'


- script: |
    npm audit || true
  displayName: 'npm security audit'   



#- task: Npm@1
 # displayName: 'npm audit'
  #inputs:
   # command: custom
   # workingDir: 'coit-frontend'
   # customCommand: 'audit --registry=https://registry.npmjs.org/'
    


#- task: Npm@1
 # displayName: 'npm audit fix'
  #inputs:
   # command: custom
    #workingDir: 'coit-frontend'
    #customCommand: 'npm audit fix --registry=https://registry.npmjs.org/ --package-lock-only'


- task: Docker@2
  inputs:
    command: 'buildAndPush'
    tags: '$(Build.BuildId)'
    containerRegistry: Docker-Hub
    repository: megha22/order-management


- task: trivy@1
  inputs:
    version: 'latest'
    image: 'megha22/order-management'






